// Generated by CoffeeScript 1.3.1
var Bomb, Empty, Explosion, Stone, Upgrade, Wood;

Empty = function() {
  this.type = 'empty';
  this.destructible = false;
  return this.walkable = true;
};

Stone = function() {
  this.type = 'stone';
  this.destructible = false;
  return this.walkable = false;
};

Wood = function(upg) {
  if (upg == null) {
    upg = false;
  }
  this.type = 'wood';
  this.destructible = true;
  this.walkable = false;
  return this.upgrade = upg;
};

Bomb = function(r, pid, t) {
  this.type = 'bomb';
  this.destructible = true;
  this.walkable = false;
  this.range = r;
  this.player_id = pid;
  return this.timer = t;
};

Explosion = function() {
  this.type = 'explosion';
  this.destructible = false;
  this.walkable = true;
  return this.count = 1;
};

/* 
	kinds of upgrades
	bomb up
	range up
	x-ray goggles?
*/


Upgrade = function(k) {
  this.type = 'upgrade';
  this.destructible = false;
  this.walkable = true;
  return this.kind = k;
};
