// Generated by CoffeeScript 1.3.1
var Bomb, Empty, Explosion, Stone, Upgrade, Wood;

Empty = (function() {

  Empty.name = 'Empty';

  function Empty() {}

  Empty.prototype.type = 'empty';

  Empty.prototype.destructible = false;

  Empty.prototype.walkable = true;

  return Empty;

})();

Stone = (function() {

  Stone.name = 'Stone';

  function Stone() {}

  Stone.prototype.type = 'stone';

  Stone.prototype.destructible = false;

  Stone.prototype.walkable = false;

  return Stone;

})();

Wood = (function() {

  Wood.name = 'Wood';

  function Wood(upg) {
    if (upg == null) {
      upg = false;
    }
    this.upgrade = upg;
  }

  Wood.prototype.type = 'wood';

  Wood.prototype.destructible = true;

  Wood.prototype.walkable = false;

  return Wood;

})();

Bomb = (function() {

  Bomb.name = 'Bomb';

  function Bomb(r, pid, t) {
    this.range = r;
    this.player_id = pid;
    this.timer = t;
  }

  Bomb.prototype.type = 'bomb';

  Bomb.prototype.destructible = true;

  Bomb.prototype.walkable = false;

  return Bomb;

})();

Explosion = (function() {

  Explosion.name = 'Explosion';

  function Explosion() {}

  Explosion.prototype.type = 'explosion';

  Explosion.prototype.destructible = false;

  Explosion.prototype.walkable = true;

  Explosion.prototype.count = 1;

  return Explosion;

})();

/* 
	kinds of upgrades
	bomb up
	range up
	x-ray goggles?
*/


Upgrade = (function() {

  Upgrade.name = 'Upgrade';

  function Upgrade(k) {
    this.kind = k;
  }

  Upgrade.prototype.type = 'upgrade';

  Upgrade.prototype.destructible = false;

  Upgrade.prototype.walkable = true;

  return Upgrade;

})();
