// Generated by CoffeeScript 1.3.1
var is_odd, movement_logic;

is_odd = function(num) {
  return num % 2 === 1;
};

movement_logic = function(player) {
  var rate, unit;
  unit = null;
  rate = null;
  switch (player.speed) {
    case 1:
      unit = 1;
      rate = 10;
      break;
    case 2:
      unit = 1;
      rate = 7;
      break;
    case 3:
      unit = 2;
      rate = 10;
      break;
    case 4:
      unit = 2;
      rate = 8;
      break;
    case 5:
      unit = 2;
      rate = 6;
      break;
    case 6:
      unit = 2;
      rate = 5;
      break;
    case 7:
      unit = 1;
      rate = 2;
      break;
    case 8:
      unit = 2;
      rate = 3;
      break;
    case 9:
      unit = 2;
      rate = 2;
      break;
    case 10:
      unit = 2;
      rate = 1;
  }
  if (player.up) {
    if (player.on_snap_x() !== player.position.x) {
      if (player.can_go_up()) {
        if (player.on_snap_x() > player.position.x) {
          player.move_right(unit);
        } else {
          player.move_left(unit);
        }
      } else {
        if (player.on_snap_x() > player.position.x) {
          player.move_left(unit);
        } else {
          player.move_right(unit);
        }
      }
    } else {
      if (player.can_go_up()) {
        player.move_up(unit);
      } else {
        player.facing = 'up';
      }
    }
  } else if (player.down) {
    if (player.on_snap_x() !== player.position.x) {
      if (player.can_go_down()) {
        if (player.on_snap_x() > player.position.x) {
          player.move_right(unit);
        } else {
          player.move_left(unit);
        }
      } else {
        if (player.on_snap_x() > player.position.x) {
          player.move_left(unit);
        } else {
          player.move_right(unit);
        }
      }
    } else {
      if (player.can_go_down()) {
        player.move_down(unit);
      } else {
        player.facing = 'down';
      }
    }
  } else if (player.left) {
    if (player.on_snap_y() !== player.position.y) {
      if (player.can_go_left()) {
        if (player.on_snap_y() > player.position.y) {
          player.move_down(unit);
        } else {
          player.move_up(unit);
        }
      } else {
        if (player.on_snap_y() > player.position.y) {
          player.move_up(unit);
        } else {
          player.move_down(unit);
        }
      }
    } else {
      if (player.can_go_left()) {
        player.move_left(unit);
      } else {
        player.facing = 'left';
      }
    }
  } else if (player.right) {
    if (player.on_snap_y() !== player.position.y) {
      if (player.can_go_right()) {
        if (player.on_snap_y() > player.position.y) {
          player.move_down(unit);
        } else {
          player.move_up(unit);
        }
      } else {
        if (player.on_snap_y() > player.position.y) {
          player.move_up(unit);
        } else {
          player.move_down(unit);
        }
      }
    } else {
      if (player.can_go_right()) {
        player.move_right(unit);
      } else {
        player.facing = 'right';
      }
    }
  }
  return player.movement = setTimeout("movement_logic(players[" + player.id + "])", rate);
};
