// Generated by CoffeeScript 1.3.1
var can_go, move_down, move_left, move_right, move_up, movement_logic;

can_go = function(player) {
  var coords, d, l, r, u;
  coords = get_grid_coords(player);
  u = true;
  d = true;
  l = true;
  r = true;
  if (coords.col === 0 && player.position.x !== 25) {
    l = true;
  } else if (player.position.x === 25 || coords.col === 0 || !objects[coords.row][coords.col - 1].walkable) {
    if (coords.col > 0 && !objects[coords.row][coords.col - 1].walkable && player.position.x - get_cartesian(coords.row, coords.col).x > 0) {
      l = true;
    } else {
      l = false;
    }
  }
  if (coords.col === 8 && player.position.x !== 425) {
    r = true;
  } else if (player.position.x === 425 || coords.col === 8 || !objects[coords.row][coords.col + 1].walkable) {
    if (coords.col < 8 && !objects[coords.row][coords.col + 1].walkable && get_cartesian(coords.row, coords.col).x - player.position.x > 0) {
      r = true;
    } else {
      r = false;
    }
  }
  if (coords.row === 0 && player.position.y !== 25) {
    u = true;
  } else if (player.position.y === 25 || coords.row === 0 || !objects[coords.row - 1][coords.col].walkable) {
    if (coords.row > 0 && !objects[coords.row - 1][coords.col].walkable && player.position.y - get_cartesian(coords.row, coords.col).y > 0) {
      u = true;
    } else {
      u = false;
    }
  }
  if (coords.row === 8 && player.position.y !== 425) {
    d = true;
  } else if (player.position.y === 425 || coords.row === 8 || !objects[coords.row + 1][coords.col].walkable) {
    if (coords.row < 8 && !objects[coords.row + 1][coords.col].walkable && get_cartesian(coords.row, coords.col).y - player.position.y > 0) {
      d = true;
    } else {
      d = false;
    }
  }
  return {
    up: u,
    down: d,
    left: l,
    right: r
  };
};

move_up = function(player) {
  player.facing = 'up';
  return player.position.y -= player.speed;
};

move_down = function(player) {
  player.facing = 'down';
  return player.position.y += player.speed;
};

move_left = function(player) {
  player.facing = 'left';
  return player.position.x -= player.speed;
};

move_right = function(player) {
  player.facing = 'right';
  return player.position.x += player.speed;
};

movement_logic = function(player) {
  if (player.up) {
    if (on_snap_x(player) !== player.position.x) {
      if (can_go(player).up) {
        if (on_snap_x(player) > player.position.x) {
          return move_right(player);
        } else {
          return move_left(player);
        }
      } else {
        if (on_snap_x(player) > player.position.x) {
          return move_left(player);
        } else {
          return move_right(player);
        }
      }
    } else {
      if (can_go(player).up) {
        return move_up(player);
      } else {
        return player.facing = 'up';
      }
    }
  } else if (player.down) {
    if (on_snap_x(player) !== player.position.x) {
      if (can_go(player).down) {
        if (on_snap_x(player) > player.position.x) {
          return move_right(player);
        } else {
          return move_left(player);
        }
      } else {
        if (on_snap_x(player) > player.position.x) {
          return move_left(player);
        } else {
          return move_right(player);
        }
      }
    } else {
      if (can_go(player).down) {
        return move_down(player);
      } else {
        return player.facing = 'down';
      }
    }
  } else if (player.left) {
    if (on_snap_y(player) !== player.position.y) {
      if (can_go(player).left) {
        if (on_snap_y(player) > player.position.y) {
          return move_down(player);
        } else {
          return move_up(player);
        }
      } else {
        if (on_snap_y(player) > player.position.y) {
          return move_up(player);
        } else {
          return move_down(player);
        }
      }
    } else {
      if (can_go(player).left) {
        return move_left(player);
      } else {
        return player.facing = 'left';
      }
    }
  } else if (player.right) {
    if (on_snap_y(player) !== player.position.y) {
      if (can_go(player).right) {
        if (on_snap_y(player) > player.position.y) {
          return move_down(player);
        } else {
          return move_up(player);
        }
      } else {
        if (on_snap_y(player) > player.position.y) {
          return move_up(player);
        } else {
          return move_down(player);
        }
      }
    } else {
      if (can_go(player).right) {
        return move_right(player);
      } else {
        return player.facing = 'right';
      }
    }
  }
};
